/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PayRouteImport } from './routes/pay'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminIdRouteImport } from './routes/_authenticated/admin/$id'
import { Route as ApiPublicDeviceHeartbeatRouteImport } from './routes/api/public/device/heartbeat'
import { Route as ApiPublicIotecCallbackRouteImport } from './routes/api/public/iotec/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIdRoute = AuthenticatedAdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicDeviceHeartbeatRoute =
  ApiPublicDeviceHeartbeatRouteImport.update({
    id: '/api/public/device/heartbeat',
    path: '/api/public/device/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIotecCallbackRoute = ApiPublicIotecCallbackRouteImport.update({
  id: '/api/public/iotec/callback',
  path: '/api/public/iotec/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pay': typeof PayRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/device/heartbeat': typeof ApiPublicDeviceHeartbeatRoute
  '/api/public/iotec/callback': typeof ApiPublicIotecCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pay': typeof PayRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/device/heartbeat': typeof ApiPublicDeviceHeartbeatRoute
  '/api/public/iotec/callback': typeof ApiPublicIotecCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pay': typeof PayRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin/$id': typeof AuthenticatedAdminIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/device/heartbeat': typeof ApiPublicDeviceHeartbeatRoute
  '/api/public/iotec/callback': typeof ApiPublicIotecCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pay'
    | '/reset-password'
    | '/admin/$id'
    | '/admin/'
    | '/api/public/device/heartbeat'
    | '/api/public/iotec/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pay'
    | '/reset-password'
    | '/admin/$id'
    | '/admin'
    | '/api/public/device/heartbeat'
    | '/api/public/iotec/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pay'
    | '/reset-password'
    | '/_authenticated/admin/$id'
    | '/_authenticated/admin/'
    | '/api/public/device/heartbeat'
    | '/api/public/iotec/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PayRoute: typeof PayRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicDeviceHeartbeatRoute: typeof ApiPublicDeviceHeartbeatRoute
  ApiPublicIotecCallbackRoute: typeof ApiPublicIotecCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$id': {
      id: '/_authenticated/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/device/heartbeat': {
      id: '/api/public/device/heartbeat'
      path: '/api/public/device/heartbeat'
      fullPath: '/api/public/device/heartbeat'
      preLoaderRoute: typeof ApiPublicDeviceHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/iotec/callback': {
      id: '/api/public/iotec/callback'
      path: '/api/public/iotec/callback'
      fullPath: '/api/public/iotec/callback'
      preLoaderRoute: typeof ApiPublicIotecCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIdRoute: typeof AuthenticatedAdminIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIdRoute: AuthenticatedAdminIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PayRoute: PayRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicDeviceHeartbeatRoute: ApiPublicDeviceHeartbeatRoute,
  ApiPublicIotecCallbackRoute: ApiPublicIotecCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
